#@data/values
---
google_analytics: |
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134922692-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134922692-1');

    const sendGoogleAnalyticsEvent = (action, category, label, value) => {
      const eventBody = {
        'event_category' : category,
        'event_label' : label,
        'value' : value
      }
      gtag('event', action, eventBody);
    }

    document.addEventListener('click', e => {
      const closestAnalytics = e.target.closest('.analytics')
      if (closestAnalytics == null) return
      const label = e.target.innerText || closestAnalytics.innerText
      sendGoogleAnalyticsEvent('click', e.target.closest('div[id]').id, label)
    });
  </script>
