apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-topic-operator
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: STRIMZI_RESOURCE_LABELS
          value: "strimzi.io/cluster=my-cluster"
        - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: STRIMZI_ZOOKEEPER_CONNECT
          value: my-cluster-zookeeper-client:2181
