name: Trivy CVE Dependency Scanner

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  trivy-scan:
    uses: carvel-dev/release-scripts/.github/workflows/trivy-scan.yml@main
    with:
      repo: carvel-dev/ytt
      tool: ytt
      goVersion: "1.21.6"
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      slackWebhookURL: ${{ secrets.SLACK_WEBHOOK_URL }}
